In [1]:
import numpy as np

In [2]:
import pandas as pd

In [27]:
df = pd.read_csv('3_Startups.csv')

In [28]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [29]:
X = df.iloc[:,:-1].values

In [30]:
y=df.iloc[:,-1].values

In [31]:
print X.shape
print type(X)
print y.shape
print type(y)

(50L, 4L)
<type 'numpy.ndarray'>
(50L,)
<type 'numpy.ndarray'>


In [32]:
#encoding categorical data
X[:5]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida']], dtype=object)

In [44]:
import sklearn

In [34]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [35]:
labelencoder = LabelEncoder()

In [36]:
X[:,3] = labelencoder.fit_transform(X[:,3])

In [37]:
print np.unique(X[:,3])
print X[:5]

[0L 1L 2L]
[[165349.2 136897.8 471784.1 2L]
 [162597.7 151377.59 443898.53 0L]
 [153441.51 101145.55 407934.54 1L]
 [144372.41 118671.85 383199.62 2L]
 [142107.34 91391.77 366168.42 1L]]


In [38]:
onehotencoder = OneHotEncoder(categorical_features=[3])

In [39]:
X = onehotencoder.fit_transform(X).toarray()

In [40]:
X[:5]

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05]])

In [41]:
X = X.astype(int)

In [42]:
X[:5]

array([[     0,      0,      1, 165349, 136897, 471784],
       [     1,      0,      0, 162597, 151377, 443898],
       [     0,      1,      0, 153441, 101145, 407934],
       [     0,      0,      1, 144372, 118671, 383199],
       [     0,      1,      0, 142107,  91391, 366168]])

In [43]:
### Split dataset

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=5,random_state=0)

In [48]:
print X_train.shape
print type(X_train)
print y_train.shape
print type(y_train)
print X_test.shape
print type(X_test)
print y_test.shape
print type(y_test)

(45L, 6L)
<type 'numpy.ndarray'>
(45L,)
<type 'numpy.ndarray'>
(5L, 6L)
<type 'numpy.ndarray'>
(5L,)
<type 'numpy.ndarray'>


In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
lin_reg = LinearRegression()

In [51]:
lin_reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [52]:
y_pred = lin_reg.predict(X_test)

In [53]:
y_pred

array([101475.56629699, 133287.07644355, 132546.48478807,  72702.37536905,
       178346.53058417])

In [54]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39])